crsa:
  recursion_depth: 1
  turns: 6
  episodes: 10
  tau_A: 2.0
  tau_B: 2.0
  reward_type: utilitarian

#meaning_space:

#priors:
#  conditional_y:
#    type: exponential_score
#    beta: 1.0

#lexicon: