matrix_file: 15x15.yaml

crsa:
  recursion_depth: 1
  turns: 800
  episodes: 10
  n: 15
  tau_A: 1.0
  tau_B: 4.0
  reward_type: utilitarian
  use_sampling: true
  sampling_mode: smart   # 'random' | 'smart'
  max_meaning_space_size: 40960